<?php

include_once "config.php";

function unsetSession1()
	{
		if(isset($_SESSION['name1']))
		{
			unset($_SESSION['name1']);
		}
		if(isset($_SESSION['surname1']))
		{
			unset($_SESSION['surname1']);
		}
		if(isset($_SESSION['car1']))
		{
			unset($_SESSION['car1']);
		}
		if(isset($_SESSION['SPZ1']))
		{
			unset($_SESSION['SPZ1']);
		}
		if(isset($_SESSION['CasPristavenia1']))
		{
			unset($_SESSION['CasPristavenia1']);
		}
		if(isset($_SESSION['CasOdchodu1']))
		{
			unset($_SESSION['CasOdchodu1']);
		}
		if(isset($_SESSION['CasPrichodu1']))
		{
			unset($_SESSION['CasPrichodu1']);
		}
		if(isset($_SESSION['DatumNakladky1']))
		{
			unset($_SESSION['DatumNakladky1']);
		}
		if(isset($_SESSION['DatumVykladky1']))
		{
			unset($_SESSION['DatumVykladky1']);
		}
		if(isset($_SESSION['partner1']))
		{
			unset($_SESSION['partner1']);
		}
		if(isset($_SESSION['depo1']))
		{
			unset($_SESSION['depo1']);
		}
	}